### ISSUE TITLE
Docker Compose Installation Error

### ISSUE THREAD

**Issue by DAMIOSKIDEV** [amrsa1/Android-Emulator-image#26]
When installing the container, I get an error:

```
 > [VNC-Service  7/10] RUN curl -sL https://deb.nodesource.com/setup_20.x | bash &&     apt-get -qqy install nodejs &&     npm install -g npm                                                                                                &&     npm i -g appium --unsafe-perm=true --allow-root &&     appium driver install uiautomator2 &&     exit 0 &&     npm cache clean &&     a                                                                                               pt-get remove --purge -y npm &&     apt-get autoremove --purge -y &&     apt-get clean &&     rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*:
0.748 2024-06-06 19:06:42 - Installing pre-requisites
0.813 Hit:1 http://deb.debian.org/debian bullseye InRelease
0.815 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
0.819 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
1.199 Reading package lists...
1.756 Reading package lists...
2.305 Building dependency tree...
2.468 Reading state information...
2.577 ca-certificates is already the newest version (20210119).
2.577 curl is already the newest version (7.74.0-1.3+deb11u11).
2.577 The following additional packages will be installed:
2.577   dirmngr gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
2.578   gpgconf gpgsm libassuan0 libksba8 libnpth0 pinentry-curses
2.578 Suggested packages:
2.578   dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
2.578   scdaemon pinentry-doc
2.662 The following NEW packages will be installed:
2.662   apt-transport-https dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent
2.662   gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libnpth0
2.663   pinentry-curses
2.697 0 upgraded, 15 newly installed, 0 to remove and 23 not upgraded.
2.697 Need to get 7825 kB of archives.
2.697 After this operation, 15.8 MB of additional disk space will be used.
2.697 Get:1 http://deb.debian.org/debian bullseye/main amd64 apt-transport-https all 2.2.4 [160 kB]
2.717 Get:2 http://deb.debian.org/debian bullseye/main amd64 libassuan0 amd64 2.5.3-7.1 [50.5 kB]
2.721 Get:3 http://deb.debian.org/debian bullseye/main amd64 gpgconf amd64 2.2.27-2+deb11u2 [548 kB]
2.728 Get:4 http://deb.debian.org/debian bullseye/main amd64 libksba8 amd64 1.5.0-3+deb11u2 [123 kB]
2.730 Get:5 http://deb.debian.org/debian bullseye/main amd64 libnpth0 amd64 1.6-3 [19.0 kB]
2.730 Get:6 http://deb.debian.org/debian bullseye/main amd64 dirmngr amd64 2.2.27-2+deb11u2 [763 kB]
2.737 Get:7 http://deb.debian.org/debian bullseye/main amd64 gnupg-l10n all 2.2.27-2+deb11u2 [1086 kB]
2.752 Get:8 http://deb.debian.org/debian bullseye/main amd64 gnupg-utils amd64 2.2.27-2+deb11u2 [905 kB]
2.759 Get:9 http://deb.debian.org/debian bullseye/main amd64 gpg amd64 2.2.27-2+deb11u2 [928 kB]
2.764 Get:10 http://deb.debian.org/debian bullseye/main amd64 pinentry-curses amd64 1.1.0-4 [64.9 kB]
2.764 Get:11 http://deb.debian.org/debian bullseye/main amd64 gpg-agent amd64 2.2.27-2+deb11u2 [669 kB]
2.768 Get:12 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-client amd64 2.2.27-2+deb11u2 [524 kB]
2.782 Get:13 http://deb.debian.org/debian bullseye/main amd64 gpg-wks-server amd64 2.2.27-2+deb11u2 [516 kB]
2.792 Get:14 http://deb.debian.org/debian bullseye/main amd64 gpgsm amd64 2.2.27-2+deb11u2 [645 kB]
2.803 Get:15 http://deb.debian.org/debian bullseye/main amd64 gnupg all 2.2.27-2+deb11u2 [825 kB]
2.984 debconf: delaying package configuration, since apt-utils is not installed
3.029 Fetched 7825 kB in 0s (52.6 MB/s)
3.051 Selecting previously unselected package apt-transport-https.
(Reading database ... 20882 files and directories currently installed.)
3.068 Preparing to unpack .../00-apt-transport-https_2.2.4_all.deb ...
3.069 Unpacking apt-transport-https (2.2.4) ...
3.096 Selecting previously unselected package libassuan0:amd64.
3.117 Preparing to unpack .../01-libassuan0_2.5.3-7.1_amd64.deb ...
3.119 Unpacking libassuan0:amd64 (2.5.3-7.1) ...
3.142 Selecting previously unselected package gpgconf.
3.144 Preparing to unpack .../02-gpgconf_2.2.27-2+deb11u2_amd64.deb ...
3.145 Unpacking gpgconf (2.2.27-2+deb11u2) ...
3.179 Selecting previously unselected package libksba8:amd64.
3.182 Preparing to unpack .../03-libksba8_1.5.0-3+deb11u2_amd64.deb ...
3.183 Unpacking libksba8:amd64 (1.5.0-3+deb11u2) ...
3.231 Selecting previously unselected package libnpth0:amd64.
3.234 Preparing to unpack .../04-libnpth0_1.6-3_amd64.deb ...
3.235 Unpacking libnpth0:amd64 (1.6-3) ...
3.260 Selecting previously unselected package dirmngr.
3.261 Preparing to unpack .../05-dirmngr_2.2.27-2+deb11u2_amd64.deb ...
3.278 Unpacking dirmngr (2.2.27-2+deb11u2) ...
3.353 Selecting previously unselected package gnupg-l10n.
3.355 Preparing to unpack .../06-gnupg-l10n_2.2.27-2+deb11u2_all.deb ...
3.356 Unpacking gnupg-l10n (2.2.27-2+deb11u2) ...
3.461 Selecting previously unselected package gnupg-utils.
3.461 Preparing to unpack .../07-gnupg-utils_2.2.27-2+deb11u2_amd64.deb ...
3.463 Unpacking gnupg-utils (2.2.27-2+deb11u2) ...
3.565 Selecting previously unselected package gpg.
3.568 Preparing to unpack .../08-gpg_2.2.27-2+deb11u2_amd64.deb ...
3.571 Unpacking gpg (2.2.27-2+deb11u2) ...
3.672 Selecting previously unselected package pinentry-curses.
3.674 Preparing to unpack .../09-pinentry-curses_1.1.0-4_amd64.deb ...
3.675 Unpacking pinentry-curses (1.1.0-4) ...
3.721 Selecting previously unselected package gpg-agent.
3.723 Preparing to unpack .../10-gpg-agent_2.2.27-2+deb11u2_amd64.deb ...
3.724 Unpacking gpg-agent (2.2.27-2+deb11u2) ...
3.769 Selecting previously unselected package gpg-wks-client.
3.771 Preparing to unpack .../11-gpg-wks-client_2.2.27-2+deb11u2_amd64.deb ...
3.772 Unpacking gpg-wks-client (2.2.27-2+deb11u2) ...
3.822 Selecting previously unselected package gpg-wks-server.
3.824 Preparing to unpack .../12-gpg-wks-server_2.2.27-2+deb11u2_amd64.deb ...
3.825 Unpacking gpg-wks-server (2.2.27-2+deb11u2) ...
3.860 Selecting previously unselected package gpgsm.
3.863 Preparing to unpack .../13-gpgsm_2.2.27-2+deb11u2_amd64.deb ...
3.864 Unpacking gpgsm (2.2.27-2+deb11u2) ...
3.929 Selecting previously unselected package gnupg.
3.931 Preparing to unpack .../14-gnupg_2.2.27-2+deb11u2_all.deb ...
3.932 Unpacking gnupg (2.2.27-2+deb11u2) ...
3.996 Setting up libksba8:amd64 (1.5.0-3+deb11u2) ...
4.019 Setting up apt-transport-https (2.2.4) ...
4.023 Setting up libnpth0:amd64 (1.6-3) ...
4.026 Setting up libassuan0:amd64 (2.5.3-7.1) ...
4.029 Setting up gnupg-l10n (2.2.27-2+deb11u2) ...
4.033 Setting up gpgconf (2.2.27-2+deb11u2) ...
4.036 Setting up gpg (2.2.27-2+deb11u2) ...
4.039 Setting up gnupg-utils (2.2.27-2+deb11u2) ...
4.042 Setting up pinentry-curses (1.1.0-4) ...
4.052 Setting up gpg-agent (2.2.27-2+deb11u2) ...
4.570 Setting up gpgsm (2.2.27-2+deb11u2) ...
4.573 Setting up dirmngr (2.2.27-2+deb11u2) ...
4.741 Setting up gpg-wks-server (2.2.27-2+deb11u2) ...
4.743 Setting up gpg-wks-client (2.2.27-2+deb11u2) ...
4.746 Setting up gnupg (2.2.27-2+deb11u2) ...
4.749 Processing triggers for libc-bin (2.31-13+deb11u5) ...
4.921 Hit:1 http://deb.debian.org/debian bullseye InRelease
4.921 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
4.921 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
5.018 Get:4 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
5.414 Get:5 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [7790 B]
5.438 Fetched 19.9 kB in 1s (36.4 kB/s)
5.438 Reading package lists...
5.920 2024-06-06 19:06:47 - Repository configured successfully. To install Node.js, run: apt-get install nodejs -y
7.259 debconf: delaying package configuration, since apt-utils is not installed
7.325 Selecting previously unselected package nodejs.
(Reading database ... 21139 files and directories currently installed.)
7.341 Preparing to unpack .../nodejs_20.14.0-1nodesource1_amd64.deb ...
7.344 Unpacking nodejs (20.14.0-1nodesource1) ...
11.45 Setting up nodejs (20.14.0-1nodesource1) ...
15.05
15.05 removed 2 packages, and changed 63 packages in 3s
15.05
15.05 24 packages are looking for funding
15.05   run `npm fund` for details
27.47 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a goo                                                                                               d and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
28.63 npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
28.65 npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
31.60
31.60 added 428 packages in 16s
31.60
31.60 58 packages are looking for funding
31.60   run `npm fund` for details
31.75 node:internal/modules/cjs/loader:1148
31.75   throw err;
31.75   ^
31.75
31.75 Error: Cannot find module '@appium/logger'
31.75 Require stack:
31.75 - /usr/lib/node_modules/appium/build/lib/logsink.js
31.75 - /usr/lib/node_modules/appium/build/lib/main.js
31.75 - /usr/lib/node_modules/appium/index.js
31.75     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
31.75     at Module._load (node:internal/modules/cjs/loader:986:27)
31.75     at Module.require (node:internal/modules/cjs/loader:1233:19)
31.75     at require (node:internal/modules/helpers:179:18)
31.75     at Object.<anonymous> (/usr/lib/node_modules/appium/build/lib/logsink.js:7:34)
31.75     at Module._compile (node:internal/modules/cjs/loader:1358:14)
31.75     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
31.75     at Module.load (node:internal/modules/cjs/loader:1208:32)
31.75     at Module._load (node:internal/modules/cjs/loader:1024:12)
31.75     at Module.require (node:internal/modules/cjs/loader:1233:19)
31.75     at require (node:internal/modules/helpers:179:18)
31.75     at Object.<anonymous> (/usr/lib/node_modules/appium/build/lib/main.js:9:19)
31.75     at Module._compile (node:internal/modules/cjs/loader:1358:14)
31.75     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
31.75     at Module.load (node:internal/modules/cjs/loader:1208:32)
31.75     at Module._load (node:internal/modules/cjs/loader:1024:12) {
31.75   code: 'MODULE_NOT_FOUND',
31.75   requireStack: [
31.75     '/usr/lib/node_modules/appium/build/lib/logsink.js',
31.75     '/usr/lib/node_modules/appium/build/lib/main.js',
31.75     '/usr/lib/node_modules/appium/index.js'
31.75   ]
31.75 }
31.75
31.75 Node.js v20.14.0
------
failed to solve: process "/bin/bash -c curl -sL https://deb.nodesource.com/setup_20.x | bash &&     apt-get -qqy install nodejs &&     npm ins                                                                                               tall -g npm &&     npm i -g appium --unsafe-perm=true --allow-root &&     appium driver install uiautomator2 &&     exit 0 &&     npm cache cl                                                                                               ean &&     apt-get remove --purge -y npm &&     apt-get autoremove --purge -y &&     apt-get clean &&     rm -Rf /tmp/* && rm -Rf /var/lib/apt                                                                                               /lists/*" did not complete successfully: exit code: 1
```

This appears when activating VNC, I don't know if it has something to do with Android-Emulator-Image.

Here's the docker-compose.yml file:

```
version: "4"
services:
# Launch emulator and appium instance
  android-service:
    image: android-emulator
    build: .
    ports:
      - 4725:4725
    container_name: android
    environment:
      - APPIUM_PORT=4725
    privileged: true
    command:
      - bash
      - -c
      - | 
         ./start_emu_headless.sh
    tty: true
    stdin_open: true
 # Starting VNC server
  VNC-Service:
    image: android-emulator
    build: .
    ports:
      - 5999:5900
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: [REDACTED]
    privileged: true
    command:
      - bash
      - -c
      - |
        $START_VNC
    tty: true
    stdin_open: true

```

**Comment by amrsa1** [comment]
Thanks @DAMIOSKIDEV for sharing this issue will check it out and get back to you

**Comment by amrsa1** [comment]
@DAMIOSKIDEV whats the OS you were using ?

**Comment by DAMIOSKIDEV** [comment]
> @DAMIOSKIDEV whats the OS you were using ?

I use Ubuntu 24.04

**Comment by amrsa1** [comment]
Try again please, i have tried its working fine.
Pull latest code and retry.
